name: unitTestActionsWorkFlow

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
      - uses: actions/checkout@v2
      - name: Setup JDK
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Make gardlew executable
      - run: chmod +x ./gradelew
      - name: run unit tests
      - run: ./gradelew test
